version: '3.6'

services:
  base:
    image: registry.digitalocean.com/hypercube/base:v3.0.0
    build: .
  debug:
    image: registry.digitalocean.com/hypercube/debug:v3.0.0
    build:
      context: .
      dockerfile: debug.Dockerfile
